### ISSUE TITLE
Failed to fetch package metadata for 'jupyterlab_apod': <HTTPError 404: 'Not Found'> 

### ISSUE THREAD

**Issue by nscozzaro** [jupyterlab/jupyterlab_apod#1]
I'm using JupyterLab 1.0.1 and at this point in the tutorial I'm able to open the tab once and it correctly shows the Astronomy Picture tab,
![image](https://user-images.githubusercontent.com/15185105/60732869-309b6580-9f19-11e9-91c0-28a0006156da.png)
But if I close it and open again, it opens a blank tab:
![image](https://user-images.githubusercontent.com/15185105/60732717-c1be0c80-9f18-11e9-98c7-b3944d049a4c.png)
In the terminal console it shows an error "Failed to fetch package metadata for 'jupyterlab_apod': <HTTPError 404: 'Not Found'> "
Please let me know how to possibly fix this error.

**Comment by jasongrout** [comment]
> at this point in the tutorial

At what step in the tutorial are we discussing here?

**Comment by nscozzaro** [comment]
Hi, sorry for the delay in response. It was this step: https://github.com/jupyterlab/jupyterlab_apod/tree/1.0-01-show-a-panel

**Comment by sahil-bansal-sb** [comment]
Same with me,
Tab works fine for once, and if closed and check again, then title properties of widget get changed,

on first opening

```
16:52:17.698  id:  apod-jupyterlab
16:52:17.698  title.lable:  Astronomy Picture
16:52:17.698  title.closable:  true
```

opening again after closing the tab
```

16:52:30.378  id:  apod-jupyterlab
16:52:30.379  title.lable:  
16:52:30.379  title.closable:  false
```

**Comment by sahil-bansal-sb** [comment]
The issue remains same in tag 1.0-06-prepare-to-publish

**Comment by ENsu** [comment]
I face the same problem.

**Comment by willibix** [comment]
I have the same issue. Tried to work around it with this (but it is definitely not right):

```
execute: () => {
    if (!widget.isAttached) {
        // Attach the widget to the main work area if it's not there
        console.log('id:', widget.id);
        console.log('title.label:', widget.title.label);
        console.log('title.closable:', widget.title.closable);
        widget.id = 'apod-jupyterlab';
        widget.title.label = 'Astronomy Picture';
        widget.title.closable = true;
        app.shell.add(widget, 'main');
        
    }
    // Activate the widget
    app.shell.activateById(widget.id);
}
```

But even after this it still not working properly. I see the label and the close button, but I can't close the tab. So something is rely wrong.

If this can help, here my conda package list:
packages in environment at /home/willibix/miniconda3/envs/jupyterlab-ext-tuto:
Name                    Version                   Build  Channel

arrow                     0.15.2                   py37_0    conda-forge
asn1crypto                1.0.1                    py37_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
bleach                    3.1.0                      py_0    conda-forge
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
cffi                      1.13.0           py37h8022711_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
cookiecutter              1.6.0                 py37_1000    conda-forge
cryptography              2.7              py37h72c5cf5_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
expat                     2.2.5             he1b5a44_1003    conda-forge
future                    0.18.0                   py37_0    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
git                       2.23.0          pl526hce37bd2_2    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                   py37_1000    conda-forge
importlib_metadata        0.23                     py37_0    conda-forge
ipykernel                 5.1.2            py37h5ca1d4c_0    conda-forge
ipython                   7.8.0            py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.15.1                   py37_0    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
jinja2-time               0.2.0                      py_2    conda-forge
json5                     0.8.5                      py_0    conda-forge
jsonschema                3.1.1                    py37_0    conda-forge
jupyter_client            5.3.3                    py37_1    conda-forge
jupyter_core              4.5.0                      py_0    conda-forge
jupyterlab                1.1.4                      py_0    conda-forge
jupyterlab_server         1.0.6                      py_0    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0    anaconda
libiconv                  1.15              h516909a_1005    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0    anaconda
libuv                     1.32.0               h516909a_0    conda-forge
markupsafe                1.1.1            py37h14c3975_0    conda-forge
mistune                   0.8.4           py37h14c3975_1000    conda-forge
more-itertools            7.2.0                      py_0    conda-forge
nbconvert                 5.6.0                    py37_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
nodejs                    12.11.1              h10a4023_0    conda-forge
notebook                  6.0.1                    py37_0    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
pandoc                    2.7.3                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.5.1                      py_0    conda-forge
pcre                      8.41              he1b5a44_1004    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
pexpect                   4.7.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pip                       19.2.3                   py37_0    conda-forge
poyo                      0.5.0                      py_0    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.10                     py_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyrsistent                0.15.4           py37h516909a_0    conda-forge
pysocks                   1.7.1                    py37_0    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pyzmq                     18.1.0           py37h1768529_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                41.4.0                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
terminado                 0.8.2                    py37_0    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
tornado                   6.0.3            py37h516909a_0    conda-forge
traitlets                 4.3.3                    py37_0    conda-forge
urllib3                   1.25.6                   py37_0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
whichcraft                0.6.1                      py_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zipp                      0.6.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge

**Comment by willibix** [comment]
Also here's the code of my index.ts file without the small work around I talk about...

```
import {
    JupyterFrontEnd, JupyterFrontEndPlugin
} from '@jupyterlab/application';

import {
    ICommandPalette, MainAreaWidget
} from '@jupyterlab/apputils';

import {
    Widget
} from '@phosphor/widgets';


/**
 * Initialization data for the jupyterlab_apod extension.
 */
const extension: JupyterFrontEndPlugin<void> = {
    id: 'jupyterlab_apod',
    autoStart: true,
    requires: [ICommandPalette],
    activate: (app: JupyterFrontEnd, palette: ICommandPalette) => {
        console.log('JupyterLab extension jupyterlab_apod is activated!');

        // Create a blank content widget inside of a MainAreaWidget
        const content = new Widget();
        const widget = new MainAreaWidget({content});
        widget.id = 'apod-jupyterlab';
        widget.title.label = 'Astronomy Picture';
        widget.title.closable = true;

        // Add an application command
        const command: string = 'apod:open';
        app.commands.addCommand(command, {
            label: 'Random Astronomy Picture',
            execute: () => {
                if (!widget.isAttached) {
                    // Attach the widget to the main work area if it's not there
                    app.shell.add(widget, 'main');
                    
                }
                // Activate the widget
                app.shell.activateById(widget.id);
            }
        });
  
        // Add the command to the palette.
        palette.addItem({command, category: 'Tutorial'});
    }
};

export default extension;
```

As you can see it's exactly like it is in the example file of this repo...

**Comment by dbudaghyan** [comment]
Here is a fast and ugly workaround:

    function activate(app: JupyterFrontEnd, palette: ICommandPalette) {
      console.log('JupyterLab extension jupyterlab_apod is activated!');

      // Create a single widget
      let content = new APODWidget();
      let widget = new MainAreaWidget({content});
      widget.id = 'apod-jupyterlab';
      widget.title.label = 'Astronomy Picture';
      widget.title.closable = true;
      // Add an application command
      const command: string = 'apod:open';
      app.commands.addCommand(command, {
        label: 'Random Astronomy Picture',
        execute: () => {
          widget.dispose();
          widget = new MainAreaWidget({content});
          widget.id = 'apod-jupyterlab';
          widget.title.label = 'Astronomy Picture';
          widget.title.closable = true;
          if (!widget.isAttached) {
            app.shell.add(widget, 'main');
          }
          // Refresh the picture in the widget
          content.update();
          // Activate the widget
          app.shell.activateById(widget.id);
        }
      });

**Comment by eugeneswalker** [comment]
I am also seeing this problem, using https://github.com/jupyterlab/jupyterlab_apod/tree/2.0-01-show-a-panel, in Firefox and Chrome.

**Comment by qTipTip** [comment]
This has to do with the disposing of the main-area widget. 
Fix here: 

https://github.com/jupyterlab/jupyterlab_apod/issues/3#issuecomment-638437677

**Comment by jasongrout** [comment]
Closing as a duplicate, then.
