### ISSUE TITLE
Jupyterlab 2.0

### ISSUE THREAD

**Issue by tomlou1** [jupyterlab/jupyterlab_apod#4]
Hi, is this extension compatible with Jupyterlab 2.0? Thanks

**Comment by jasongrout** [comment]
Yes.

**Comment by jasongrout** [comment]
FYI, this extension goes with the tutorial at https://jupyterlab.readthedocs.io/en/stable/developer/extension_tutorial.html

**Comment by lotusvpnpro** [comment]
I used "jupyter labextension install jupyterlab_apod-2.0" to install this extension.
Then, Jupyterlab gives many errors in the backend terminal: 

      File "/Users/mariolzx/opt/anaconda3/envs/jupyterlab-ext/lib/python3.8/site-packages/jupyterlab/commands.py", line 541, in get_latest_compatible_package_versions
        return handler.latest_compatible_package_versions(names)
      File "/Users/mariolzx/opt/anaconda3/envs/jupyterlab-ext/lib/python3.8/site-packages/jupyterlab/commands.py", line 1659, in latest_compatible_package_versions
        for version, data in sorted(versions.items(),
    AttributeError: 'list' object has no attribute 'items'
[W 00:34:01.164 LabApp] Unhandled error
[E 00:34:01.164 LabApp] {
      "Host": "localhost:8889",
      "Connection": "keep-alive",
      "Authorization": "token 9036729e7e9169af148077e9013f87175c6a321bfdd7c2ed",
      "Sec-Fetch-Dest": "empty",
      "X-Xsrftoken": "2|c7bf5288|ad42adaaeaf06d907f6001d1362da6c1|1584587174",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36",
      "Dnt": "1",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Referer": "http://localhost:8889/lab/workspaces/auto-E",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
      "Cookie": "_xsrf=2|c7bf5288|ad42adaaeaf06d907f6001d1362da6c1|1584587174; username-localhost-8888=\"2|1:0|10:1584670862|23:username-localhost-8888|44:YzM2M2YwMWEzNDIzNGExOGJkNmYzNDc4N2FlNjQxMWE=|94b8e91ab6b726d54eebae3e8a07699302286bec38506357e26c5c7268e29894\"; username-localhost-8889=\"2|1:0|10:1584851640|23:username-localhost-8889|44:N2RiMzgxODc3NDRkNGQ5NzliN2ZjOTg0NWVkOWQ5MGY=|ce448ab07f719f6df24d3924e946a8d6116c84f18ab5f79139e5c3af97613cd8\""
    }
[E 00:34:01.164 LabApp] 500 GET /lab/api/extensions?1584851641130 (::1) 27.97ms referer=http://localhost:8889/lab/wor


In chrome, when I click extension manager, it prompts "Error communicating with server extension. Consult the documentation for how to ensure that it is enabled. 
Reason given: Error: 500 (Internal Server Error)"

Do you know why? Thanks a lot!

**Comment by tomlou1** [comment]
I used "jupyter labextension install jupyterlab_apod-2.0" to install this extension.
Then, Jupyterlab gives many errors in the backend terminal:

  File "/Users/mariolzx/opt/anaconda3/envs/jupyterlab-ext/lib/python3.8/site-packages/jupyterlab/commands.py", line 541, in get_latest_compatible_package_versions
    return handler.latest_compatible_package_versions(names)
  File "/Users/mariolzx/opt/anaconda3/envs/jupyterlab-ext/lib/python3.8/site-packages/jupyterlab/commands.py", line 1659, in latest_compatible_package_versions
    for version, data in sorted(versions.items(),
AttributeError: 'list' object has no attribute 'items'
[W 00:34:01.164 LabApp] Unhandled error
[E 00:34:01.164 LabApp] {
"Host": "localhost:8889",
"Connection": "keep-alive",
"Authorization": "token 9036729e7e9169af148077e9013f87175c6a321bfdd7c2ed",
"Sec-Fetch-Dest": "empty",
"X-Xsrftoken": "2|c7bf5288|ad42adaaeaf06d907f6001d1362da6c1|1584587174",
"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36",
"Dnt": "1",
"Content-Type": "application/json",
"Accept": "/",
"Sec-Fetch-Site": "same-origin",
"Sec-Fetch-Mode": "cors",
"Referer": "http://localhost:8889/lab/workspaces/auto-E",
"Accept-Encoding": "gzip, deflate, br",
"Accept-Language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
"Cookie": "_xsrf=2|c7bf5288|ad42adaaeaf06d907f6001d1362da6c1|1584587174; username-localhost-8888="2|1:0|10:1584670862|23:username-localhost-8888|44:YzM2M2YwMWEzNDIzNGExOGJkNmYzNDc4N2FlNjQxMWE=|94b8e91ab6b726d54eebae3e8a07699302286bec38506357e26c5c7268e29894"; username-localhost-8889="2|1:0|10:1584851640|23:username-localhost-8889|44:N2RiMzgxODc3NDRkNGQ5NzliN2ZjOTg0NWVkOWQ5MGY=|ce448ab07f719f6df24d3924e946a8d6116c84f18ab5f79139e5c3af97613cd8""
}
[E 00:34:01.164 LabApp] 500 GET /lab/api/extensions?1584851641130 (::1) 27.97ms referer=http://localhost:8889/lab/wor

In chrome, when I click extension manager, it prompts "Error communicating with server extension. Consult the documentation for how to ensure that it is enabled.
Reason given: Error: 500 (Internal Server Error)"

Do you know why? Thanks a lot!

**Comment by bnuhero** [comment]
Hi @hkbluesky ,

This package is NOT published yet. So you can't install it by running:
`jupyter labextension install jupyterlab_apod-2.0`
or
`jupyter labextension install @jupyterlab/jupyterlab_apod` (as specified in README.md)

You can try a development install instead.

**Comment by blink1073** [comment]
I pushed `@jupyterlab/jupyterlab_apod@2.0.0`.

**Comment by tomlou1** [comment]
The extension has been installed. However, when I type "Astronomy" according to this image:
https://jupyterlab.readthedocs.io/en/stable/_images/extension_tutorial_complete.png,
the extension does not show up in the tutorial. So, how do I run this extension?

**Comment by bnuhero** [comment]
Install the extension first.

```shell
conda create env --name test python nodejs # Python 3.8.2, Node.js v10.13.0, npm@6.4.1
conda activate test
pip install jupyterlab # v2.0.1 installed.
jupyter labextension install @jupyterlab/jupyterlab_apod
```

Search `Astronomy` and click `Random Astronomy Picture`. It worked like a charm.

<img width="1920" alt="Random Astronomy Picture" src="https://user-images.githubusercontent.com/1662386/78021999-c8ce5a00-7386-11ea-9ea6-347961e902fc.png">

**Comment by tomlou1** [comment]
Cool. It works now. Thanks

**Comment by jasongrout** [comment]
Great!
