### ISSUE TITLE
extension does not show up

### ISSUE THREAD

**Issue by tomlou1** [jupyterlab/jupyterlab_apod#5]
Hi,
I followed this instruction: https://jupyterlab.readthedocs.io/en/stable/developer/extension_tutorial.html
The extension has been installed. However, when I type "Astronomy" according to this image:
https://jupyterlab.readthedocs.io/en/stable/_images/extension_tutorial_complete.png,
the extension does not show up in the tutorial. So, how do I run this extension?

**Comment by jasongrout** [comment]
The tutorial gives instructions for installing and running this tutorial. I realize it's been a while since you asked this question, but if you are still interested in investigating, can you list out explicitly what you did try?

**Comment by fcollonval** [comment]
Closing as stale
